# Generated by Django 4.1.5 on 2023-01-28 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_user_address_alter_user_date_joined_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 28, 8, 22, 57, 367315, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
