# Generated by Django 4.1.5 on 2023-01-28 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 28, 8, 24, 2, 817196, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
